name: Build and deploy the Swansea Cyber Clinic website

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    concurrency: ci-${{ github.reference }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '17'
          cache: 'npm'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'
          bundler-cache: true

      - name: Build
        run: |
          npm run build
          bundle exec jekyll build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: _site

      